version: '3'

services:
  frontend:
    image: gnsnghm/pgqc-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:5000

  backend:
    image: gnsnghm/pgqc-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend/config.json:/app/config.json
    environment:
      - RECORD_DB_HOST=db
      - RECORD_DB_PORT=5432
      - RECORD_DB_NAME=compare_log
      - RECORD_DB_USER=postgres
      - RECORD_DB_PASSWORD=postgres00
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres00
      POSTGRES_DB: compare_log
    ports:
      - "5455:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
